### ISSUE TITLE
Homebrew upgrade error: mailbundle not found

### ISSUE THREAD

**Issue by bnavigator** [Free-GPGMail/Free-GPGMail#81]
FWIW: The issue when upgrading still exists and is not caused by the disk access permission for the terminal app (I have full disk access enabled for the terminal).
When I tried to upgrade today, I got the same error:
```
Error: free-gpgmail: It seems the Generic Artifact source '/Users/jl-stellar/Library/Mail/Bundles/Free-GPGMail_7.mailbundle' is not there.
```
The plugin was still accessible in Apple Mail, but showed the old version 7.0.
After a restart of the app, the plugin was gone from Apple Mail (Tab in settings gone, and plugn no longer listed under "Manage Plugins").
Running `brew upgrade` again resulted in the same error. However, running `brew install --cask free-gpgmail' resulted in the error "is already installed".
What worked in the end was `brew reinstall --cask free-gpgmail`. The command was executed successfully and after a restart of Apple Mail, the plugin could again be activated under "Manage Plugins" and then was back and working.

_Originally posted by @jl-stellar in https://github.com/Free-GPGMail/Free-GPGMail/issues/53#issuecomment-1488732074_

**Comment by bnavigator** [comment]
If this is a bug and not specific to the user istallation, it must be fixed in the cask, not in the Free-GPGMail repository.

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/f/free-gpgmail.rb

**Comment by jl-stellar** [comment]
Thanks, I've asked in the discussions on homebrew-cask if the issue is specific to my installation or more of a general problem with the cask.

**Comment by bnavigator** [comment]
For the record:  The discussion is here: https://github.com/orgs/Homebrew/discussions/4365

**Comment by bnavigator** [comment]
There were several updates to the cask which look to me like they could have fixed the issue.

**Comment by jl-stellar** [comment]
Unfortunately this issue still seems to exist.

What works for me is the following workflow:
* The usual `brew update` and `brew upgrade`
* `brew reinstall free-gpgmail`
* Quit and restart Mail.app
* In Mail.app settings, ob tab "General" click on button "Manage Plugins..."
* Activate "Free-GPGMail_7.mailbundle"
* Quit and restart Mail.app

**Note:** As @bnavigator pointed out above, this is a homebrew issue. I just wanted to post the workaround in case it is useful for others.
